CREATE DATABASE customer_behaviour_analysis_db

USE customer_behaviour_analysis_db;
DROP TABLE customer_analysis
select * from customer_analysis limit 10

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender ,SUM(purchase_amount) as revenue from customer_analysis GROUP BY gender

--Q2. Which customers used a discount but still spent more than or equal to the average purchase amount? 
select customer_id, purchase_amount from customer_analysis where discount_applied="YES" and purchase_amount>= (select avg(purchase_amount) from customer_analysis)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as average_product_rating from customer_analysis GROUP BY item_purchased order by avg(review_rating) desc limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),2) as avg_amount_spent from customer_analysis where shipping_type in ("Express" , "Standard") group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spent, round(sum(purchase_amount),2) as total_revenue from customer_analysis group by subscription_status order by total_revenue, avg_spent desc


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(100* sum(case when subscription_status = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate from customer_analysis group by item_purchased order by discount_rate desc limit 5


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

with customer_type as (select customer_id, previous_purchases, 
CASE WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_analysis)

select customer_segment,count(*) AS "number_of_customers" 
from customer_type 
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category? 
Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_analysis
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3; 


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_analysis
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount)as total_revenue from customer_analysis group by age_group order by total_revenue desc



